### ISSUE TITLE
Update a Payment Type

### ISSUE THREAD

**Issue by broach44** [BillyCranston/Bangazon-Tinkr#20]
# User Story
As a user that wants to buy stuff, I would like to be able to update my payment type(s).
# AC
**GIVEN** I would like to change information on my payment type
**WHEN** I edit the payment type
**THEN** The payment type information in the database should be updated
# Dev Notes
- Create a Put Request on the userController called UpdatePmtTypeById that takes in the pmtTypeId
- Check that the payment type exists
- Create a method in the UserRepo called UpdatePmtType that will allow the user to update the entire payment type entry (except probably the id).
- Return the updated pmtType

**Comment by aleshakay** [comment]
💯
