### ISSUE TITLE
Bug Fix: Fix the ability for user to add multiple of the same product id into their cart

### ISSUE THREAD

**Issue by broach44** [BillyCranston/Bangazon-Tinkr#81]
# Dev Notes

**PROBLEM**  User is able to add multiple items with the same product id into their cart.  This creates an issue as there is not multiple items for the buyer to purchase and the system is not able to create unique keys
**ANALYSIS**  This is occurring because there is some validation logic that will need to be added to not allow for the same orderId to have more than one of a product id
**PROPOSED SOLUTION**
- On the methods in the api will need to add a request that checks whether the product id for a particular item already exists in the Line Item table where the order id equals the order that is trying to receive an additional line item.
- Add a second layer of validation on the front end that checks this as well so there are no errors being received and bad data is not getting to the db.

**Comment by aleshakay** [comment]
💯
