### ISSUE TITLE
Delete Rubbish

### ISSUE THREAD

**Issue by broach44** [BillyCranston/Bangazon-Tinkr#9]
# User Story
As a user, if I change my mind and would not like to sell a piece of rubbish I want to be able to delete it from the database.

# AC
**GIVEN** I wish to delete an item
**WHEN** I delete the item
**THEN** The item will be deleted from the database

# Dev Notes
- Create a Delete request called deleteRubbishById in the rubbish controller that will take in the id of the rubbish to be deleted.
- Check that the rubbish exists and return not found if it does not exist.
- Create a method in the Rubbish controller called deleteRubbish that will remove the record from the database.

**Comment by ghost** [comment]
👍
